import { Categorytype } from '@shared/ui/category/types'
import { MdOutlineLocationOn } from 'react-icons/md'

const ProvinceIcon = <MdOutlineLocationOn size={20} />

export const CurrencyConstants = [
  { value: 'AFN', label: 'Afghani (AFN)' },
  { value: 'USD', label: 'Dollar (USD)' },
]

export const ProvinceConstants: (Categorytype & {
  districts: { value: string; label: string }[]
})[] = [
  {
    id: 1,
    label: 'Badakhshan',
    icon: ProvinceIcon,
    value: 'badakhshan',
    districts: [
      { value: 'arghanj_khwa', label: 'Arghanj Khwa' },
      { value: 'argo', label: 'Argo' },
      { value: 'baharak', label: 'Baharak' },
      { value: 'darayim', label: 'Darayim' },
      { value: 'fayzabad', label: 'Fayzabad' },
      { value: 'ishkashim', label: 'Ishkashim' },
      { value: 'jurm', label: 'Jurm' },
      { value: 'khash', label: 'Khash' },
      { value: 'khwahan', label: 'Khwahan' },
      { value: 'kishim', label: 'Kishim' },
      { value: 'kohistan', label: 'Kohistan' },
      { value: 'kuf_ab', label: 'Kuf Ab' },
      { value: 'kuran_wa_munjan', label: 'Kuran wa Munjan' },
      { value: 'maimay', label: 'Maimay' },
      { value: 'nusay', label: 'Nusay' },
      { value: 'raghistan', label: 'Raghistan' },
      { value: 'shahri_buzurg', label: 'Shahri Buzurg' },
      { value: 'sheghnan', label: 'Sheghnan' },
      { value: 'shekay', label: 'Shekay' },
      { value: 'shuhada', label: 'Shuhada' },
      { value: 'tagab', label: 'Tagab' },
      { value: 'tishkan', label: 'Tishkan' },
      { value: 'wakhan', label: 'Wakhan' },
      { value: 'warduj', label: 'Warduj' },
      { value: 'yaftali_sufla', label: 'Yaftali Sufla' },
      { value: 'yamgan', label: 'Yamgan' },
      { value: 'yawan', label: 'Yawan' },
      { value: 'zebak', label: 'Zebak' },
    ],
  },
  {
    id: 2,
    label: 'Badghis',
    icon: ProvinceIcon,
    value: 'badghis',
    districts: [
      { value: 'ab_kamari', label: 'Ab Kamari' },
      { value: 'ghormach', label: 'Ghormach' },
      { value: 'jawand', label: 'Jawand' },
      { value: 'muqur', label: 'Muqur' },
      { value: 'bala_murghab', label: 'Bala Murghab' },
      { value: 'qadis', label: 'Qadis' },
      { value: 'qala_i_naw', label: 'Qala i Naw' },
    ],
  },
  {
    id: 3,
    label: 'Baghlan',
    icon: ProvinceIcon,
    value: 'baghlan',
    districts: [
      { value: 'andarab', label: 'Andarab' },
      { value: 'baghlani_jadid', label: 'Baghlani Jadid' },
      { value: 'burka', label: 'Burka' },
      { value: 'dahana_i_ghuri', label: 'Dahana-I-Ghuri' },
      { value: 'dih_salah', label: 'Dih Salah' },
      { value: 'dushi', label: 'Dushi' },
      { value: 'farang_wa_gharu', label: 'Farang Wa Gharu' },
      { value: 'guzargahi_nur', label: 'Guzargahi Nur' },
      { value: 'khinjan', label: 'Khinjan' },
      { value: 'khost_wa_fereng', label: 'Khost Wa Fereng' },
      { value: 'khwaja_hijran', label: 'Khwaja Hijran' },
      { value: 'nahrin', label: 'Nahrin' },
      { value: 'puli_hisar', label: 'Puli Hisar' },
      { value: 'puli_khumri', label: 'Puli Khumri' },
      { value: 'tala_wa_barfak', label: 'Tala wa Barfak' },
    ],
  },
  {
    id: 4,
    label: 'Balkh',
    icon: ProvinceIcon,
    value: 'balkh',
    districts: [
      { value: 'balkh', label: 'Balkh' },
      { value: 'charbolak', label: 'Charbolak' },
      { value: 'charkint', label: 'Charkint' },
      { value: 'chimtal', label: 'Chimtal' },
      { value: 'dawlatabad', label: 'Dawlatabad' },
      { value: 'dihdadi', label: 'Dihdadi' },
      { value: 'kaldar', label: 'Kaldar' },
      { value: 'khulm', label: 'Khulm' },
      { value: 'kishindih', label: 'Kishindih' },
      { value: 'marmul', label: 'Marmul' },
      { value: 'mazar_e_sharif', label: 'Mazar-e-Sharif' },
      { value: 'nahri_shahi', label: 'Nahri Shahi' },
      { value: 'sholgara', label: 'Sholgara' },
      { value: 'shortepa', label: 'Shortepa' },
      { value: 'zari', label: 'Zari' },
    ],
  },
  {
    id: 5,
    label: 'Bamyan',
    icon: ProvinceIcon,
    value: 'bamyan',
    districts: [
      { value: 'bamyan', label: 'Bamyan' },
      { value: 'kahmard', label: 'Kahmard' },
      { value: 'panjab', label: 'Panjab' },
      { value: 'sayghan', label: 'Sayghan' },
      { value: 'shibar', label: 'Shibar' },
      { value: 'waras', label: 'Waras' },
      { value: 'yakawlang', label: 'Yakawlang' },
    ],
  },
  {
    id: 6,
    label: 'Daykundi',
    icon: ProvinceIcon,
    value: 'daykundi',
    districts: [
      { value: 'ishtarlay', label: 'Ishtarlay' },
      { value: 'kijran', label: 'Kijran' },
      { value: 'khedir', label: 'Khedir' },
      { value: 'kitti', label: 'Kitti' },
      { value: 'miramor', label: 'Miramor' },
      { value: 'nili', label: 'Nili' },
      { value: 'sangi_takht', label: 'Sangi Takht' },
      { value: 'shahristan', label: 'Shahristan' },
    ],
  },
  {
    id: 7,
    label: 'Farah',
    icon: ProvinceIcon,
    value: 'farah',
    districts: [
      { value: 'anar_dara', label: 'Anar Dara' },
      { value: 'bakwa', label: 'Bakwa' },
      { value: 'bala_buluk', label: 'Bala Buluk' },
      { value: 'farah', label: 'Farah' },
      { value: 'gulistan', label: 'Gulistan' },
      { value: 'khaki_safed', label: 'Khaki Safed' },
      { value: 'lash_wa_juwayn', label: 'Lash Wa Juwayn' },
      { value: 'pur_chaman', label: 'Pur Chaman' },
      { value: 'pusht_rod', label: 'Pusht Rod' },
      { value: 'qala_i_kah', label: 'Qala-I-Kah' },
      { value: 'shib_koh', label: 'Shib Koh' },
    ],
  },
  {
    id: 8,
    label: 'Faryab',
    icon: ProvinceIcon,
    value: 'faryab',
    districts: [
      { value: 'almar', label: 'Almar' },
      { value: 'andkhoy', label: 'Andkhoy' },
      { value: 'bilchiragh', label: 'Bilchiragh' },
      { value: 'dawlat_abad', label: 'Dawlat Abad' },
      { value: 'gurziwan', label: 'Gurziwan' },
      { value: 'khani_char_bagh', label: 'Khani Char Bagh' },
      { value: 'khwaja_sabz_posh', label: 'Khwaja Sabz Posh' },
      { value: 'kohistan', label: 'Kohistan' },
      { value: 'maymana', label: 'Maymana' },
      { value: 'pashtun_kot', label: 'Pashtun Kot' },
      { value: 'qaramqol', label: 'Qaramqol' },
      { value: 'qaysar', label: 'Qaysar' },
      { value: 'qurghan', label: 'Qurghan' },
      { value: 'shirin_tagab', label: 'Shirin Tagab' },
    ],
  },
  {
    id: 9,
    label: 'Ghazni',
    icon: ProvinceIcon,
    value: 'ghazni',
    districts: [
      { value: 'ab_band', label: 'Ab Band' },
      { value: 'ajristan', label: 'Ajristan' },
      { value: 'andar', label: 'Andar' },
      { value: 'deh_yak', label: 'Deh Yak' },
      { value: 'gelan', label: 'Gelan' },
      { value: 'ghazni', label: 'Ghazni' },
      { value: 'giro', label: 'Giro' },
      { value: 'jaghori', label: 'Jaghori' },
      { value: 'jaghatu', label: 'Jaghatū' },
      { value: 'khogyani', label: 'Khogyani' },
      { value: 'khwaja_umari', label: 'Khwaja Umari' },
      { value: 'malistan', label: 'Malistan' },
      { value: 'muqur', label: 'Muqur' },
      { value: 'nawa', label: 'Nawa' },
      { value: 'nawur', label: 'Nawur' },
      { value: 'qarabagh', label: 'Qarabagh' },
      { value: 'rashidan', label: 'Rashidan' },
      { value: 'waghaz', label: 'Waghaz' },
      { value: 'zana_khan', label: 'Zana Khan' },
    ],
  },
  {
    id: 10,
    label: 'Ghor',
    icon: ProvinceIcon,
    value: 'ghor',
    districts: [
      { value: 'chaghcharan', label: 'Chaghcharan' },
      { value: 'charsada', label: 'Charsada' },
      { value: 'dawlat_yar', label: 'Dawlat Yar' },
      { value: 'du_layna', label: 'Du Layna' },
      { value: 'lal_wa_sarjangal', label: 'Lal wa Sarjangal' },
      { value: 'marghab', label: 'Marghab' },
      { value: 'pasaband', label: 'Pasaband' },
      { value: 'saghar', label: 'Saghar' },
      { value: 'shahrak', label: 'Shahrak' },
      { value: 'taywara', label: 'Taywara' },
      { value: 'tulak', label: 'Tulak' },
    ],
  },
  {
    id: 11,
    label: 'Helmand',
    icon: ProvinceIcon,
    value: 'helmand',
    districts: [
      { value: 'baghran', label: 'Baghran' },
      { value: 'dishu', label: 'Dishu' },
      { value: 'garmsir', label: 'Garmsir' },
      { value: 'kajaki', label: 'Kajaki' },
      { value: 'khanashin', label: 'Khanashin' },
      { value: 'lashkargah', label: 'Lashkargah' },
      { value: 'marjah', label: 'Marjah' },
      { value: 'musa_qala', label: 'Musa Qala' },
      { value: 'nad_ali', label: 'Nad Ali' },
      { value: 'grishk', label: 'Grishk' },
      { value: 'nawa_i_barakzayi', label: 'Nawa-I-Barakzayi' },
      { value: 'nawzad', label: 'Nawzad' },
      { value: 'sangin', label: 'Sangin' },
      { value: 'washir', label: 'Washir' },
    ],
  },
  {
    id: 12,

    label: 'Herat',
    icon: ProvinceIcon,
    value: 'herat',
    districts: [
      { value: 'adraskan', label: 'Adraskan' },
      { value: 'chishti_sharif', label: 'Chishti Sharif' },
      { value: 'farsi', label: 'Farsi' },
      { value: 'ghoryan', label: 'Ghoryan' },
      { value: 'gulran', label: 'Gulran' },
      { value: 'guzara', label: 'Guzara' },
      { value: 'herat', label: 'Herat' },
      { value: 'injil', label: 'Injil' },
      { value: 'karukh', label: 'Karukh' },
      { value: 'kohsan', label: 'Kohsan' },
      { value: 'kushk', label: 'Kushk' },
      { value: 'kushki_kuhna', label: 'Kushki Kuhna' },
      { value: 'obe', label: 'Obe' },
      { value: 'pashtun_zarghun', label: 'Pashtun Zarghun' },
      { value: 'shindand', label: 'Shindand' },
      { value: 'zinda_jan', label: 'Zinda Jan' },
    ],
  },
  {
    id: 13,

    label: 'Jowzjan',
    icon: ProvinceIcon,
    value: 'jowzjan',
    districts: [
      { value: 'aqcha', label: 'Aqcha' },
      { value: 'darzab', label: 'Darzab' },
      { value: 'fayzabad', label: 'Fayzabad' },
      { value: 'khamyab', label: 'Khamyab' },
      { value: 'khaniqa', label: 'Khaniqa' },
      { value: 'khwaja_du_koh', label: 'Khwaja Du Koh' },
      { value: 'mardyan', label: 'Mardyan' },
      { value: 'mingajik', label: 'Mingajik' },
      { value: 'qarqin', label: 'Qarqin' },
      { value: 'qush_tepa', label: 'Qush Tepa' },
      { value: 'sheberghan', label: 'Sheberghan' },
    ],
  },
  {
    id: 14,

    label: 'Kabul',
    icon: ProvinceIcon,
    value: 'kabul',
    districts: [
      { value: 'bagrami', label: 'Bagrami' },
      { value: 'chahar_asyab', label: 'Chahar Asyab' },
      { value: 'deh_sabz', label: 'Deh Sabz' },
      { value: 'farza', label: 'Farza' },
      { value: 'guldara', label: 'Guldara' },
      { value: 'istalif', label: 'Istalif' },
      { value: 'kabul', label: 'Kabul' },
      { value: 'kalakan', label: 'Kalakan' },
      { value: 'khaki_jabbar', label: 'Khaki Jabbar' },
      { value: 'mir_bacha_kot', label: 'Mir Bacha Kot' },
      { value: 'mussahi', label: 'Mussahi' },
      { value: 'paghman', label: 'Paghman' },
      { value: 'qarabagh', label: 'Qarabagh' },
      { value: 'shakardara', label: 'Shakardara' },
      { value: 'surobi', label: 'Surobi' },
    ],
  },
  {
    id: 15,

    label: 'Kandahar',
    icon: ProvinceIcon,
    value: 'kandahar',
    districts: [
      { value: 'arghandab', label: 'Arghandab' },
      { value: 'arghistan', label: 'Arghistan' },
      { value: 'daman', label: 'Daman' },
      { value: 'ghorak', label: 'Ghorak' },
      { value: 'kandahar', label: 'Kandahar' },
      { value: 'khakrez', label: 'Khakrez' },
      { value: 'maruf', label: 'Maruf' },
      { value: 'maiwand', label: 'Maiwand' },
      { value: 'miyanishin', label: 'Miyanishin' },
      { value: 'nesh', label: 'Nesh' },
      { value: 'panjwayi', label: 'Panjwayi' },
      { value: 'reg', label: 'Reg' },
      { value: 'shah_wali_kot', label: 'Shah Wali Kot' },
      { value: 'shorabak', label: 'Shorabak' },
      { value: 'spin_boldak', label: 'Spin Boldak' },
      { value: 'takhta_pul', label: 'Takhta-pul' },
      { value: 'zhari', label: 'Zhari' },
      { value: 'dand', label: 'Dand' },
    ],
  },
  {
    id: 16,

    label: 'Kapisa',
    icon: ProvinceIcon,
    value: 'kapisa',
    districts: [
      { value: 'alasay', label: 'Alasay' },
      { value: 'hesa_awal_kohistan', label: 'Hesa Awal Kohistan' },
      { value: 'hesa_duwum_kohistan', label: 'Hesa Duwum Kohistan' },
      { value: 'koh_band', label: 'Koh Band' },
      { value: 'mahmud_raqi', label: 'Mahmud Raqi' },
      { value: 'nijrab', label: 'Nijrab' },
      { value: 'tagab', label: 'Tagab' },
    ],
  },
  {
    id: 17,

    label: 'Khost',
    icon: ProvinceIcon,
    value: 'khost',
    districts: [
      { value: 'bak', label: 'Bak' },
      { value: 'gurbuz', label: 'Gurbuz' },
      { value: 'jaji_maydan', label: 'Jaji Maydan' },
      { value: 'khost', label: 'Khost' },
      { value: 'mandozayi', label: 'Mandozayi' },
      { value: 'musa_khel', label: 'Musa Khel' },
      { value: 'nadir_shah_kot', label: 'Nadir Shah Kot' },
      { value: 'qalandar', label: 'Qalandar' },
      { value: 'sabari', label: 'Sabari' },
      { value: 'shamal', label: 'Shamal' },
      { value: 'spera', label: 'Spera' },
      { value: 'tani', label: 'Tani' },
      { value: 'tirazayi', label: 'Tirazayi' },
    ],
  },
  {
    id: 18,

    label: 'Kunar',
    icon: ProvinceIcon,
    value: 'kunar',
    districts: [
      { value: 'asadabad', label: 'Asadabad' },
      { value: 'bar_kunar', label: 'Bar Kunar' },
      { value: 'chapa_dara', label: 'Chapa Dara' },
      { value: 'chawkay', label: 'Chawkay' },
      { value: 'dangam', label: 'Dangam' },
      { value: 'dara_i_pech', label: 'Dara-I-Pech' },
      { value: 'ghaziabad', label: 'Ghaziabad' },
      { value: 'khas_kunar', label: 'Khas Kunar' },
      { value: 'marawara', label: 'Marawara' },
      { value: 'narang_aw_badil', label: 'Narang Aw Badil' },
      { value: 'nari', label: 'Nari' },
      { value: 'nurgal', label: 'Nurgal' },
      { value: 'shaigal', label: 'Shaigal' },
      { value: 'shultan', label: 'Shultan' },
      { value: 'sirkani', label: 'Sirkani' },
      { value: 'wata_pur', label: 'Wata Pur' },
    ],
  },
  {
    id: 19,
    label: 'Kunduz',
    icon: ProvinceIcon,
    value: 'kunduz',
    districts: [
      { value: 'ali_abad', label: 'Ali Abad' },
      { value: 'archi', label: 'Archi' },
      { value: 'chardara', label: 'Chardara' },
      { value: 'imam_sahib', label: 'Imam Sahib' },
      { value: 'khan_abad', label: 'Khan Abad' },
      { value: 'kunduz', label: 'Kunduz' },
      { value: 'qalay_i_zal', label: 'Qalay-I-Zal' },
    ],
  },
  {
    id: 20,
    label: 'Laghman',
    icon: ProvinceIcon,
    value: 'laghman',
    districts: [
      { value: 'alingar', label: 'Alingar' },
      { value: 'alishing', label: 'Alishing' },
      { value: 'dawlat_shah', label: 'Dawlat Shah' },
      { value: 'mihtarlam', label: 'Mihtarlam' },
      { value: 'qarghayi', label: 'Qarghayi' },
    ],
  },
  {
    id: 21,
    label: 'Logar',
    icon: ProvinceIcon,
    value: 'logar',
    districts: [
      { value: 'azra', label: 'Azra' },
      { value: 'baraki_barak', label: 'Baraki Barak' },
      { value: 'charkh', label: 'Charkh' },
      { value: 'kharwar', label: 'Kharwar' },
      { value: 'khoshi', label: 'Khoshi' },
      { value: 'mohammad_agha', label: 'Mohammad Agha' },
      { value: 'puli_alam', label: 'Puli Alam' },
    ],
  },
  {
    id: 22,
    label: 'Nangarhar',
    icon: ProvinceIcon,
    value: 'nangarhar',
    districts: [
      { value: 'jalalabad', label: 'Jalalabad' },
      { value: 'haska_meyna', label: 'Haska Meyna' },
      { value: 'shinwar', label: 'Shinwar' },
      { value: 'achin', label: 'Achin' },
      { value: 'bihsud', label: 'Bihsud' },
      { value: 'chaparhar', label: 'Chaparhar' },
      { value: 'darai_nur', label: 'Darai Nur' },
      { value: 'bati_kot', label: 'Bati Kot' },
      { value: 'dur_baba', label: 'Dur Baba' },
      { value: 'goshta', label: 'Goshta' },
      { value: 'hisarak', label: 'Hisarak' },
      { value: 'kama', label: 'Kama' },
      { value: 'khogyani', label: 'Khogyani' },
      { value: 'kot', label: 'Kot' },
      { value: 'kuz_kunar', label: 'Kuz Kunar' },
      { value: 'lal_pur', label: 'Lal Pur' },
      { value: 'momand_dara', label: 'Momand Dara' },
      { value: 'nazyan', label: 'Nazyan' },
      { value: 'pachir_aw_agam', label: 'Pachir Aw Agam' },
      { value: 'rodat', label: 'Rodat' },
      { value: 'sherzad', label: 'Sherzad' },
      { value: 'surkh_rod', label: 'Surkh Rod' },
    ],
  },
  {
    id: 23,
    label: 'Nimroz',
    icon: ProvinceIcon,
    value: 'nimroz',
    districts: [
      { value: 'chahar_burjak', label: 'Chahar Burjak' },
      { value: 'chakhansur', label: 'Chakhansur' },
      { value: 'kang', label: 'Kang' },
      { value: 'khash_rod', label: 'Khash Rod' },
      { value: 'zaranj', label: 'Zaranj' },
    ],
  },
  {
    id: 24,
    label: 'Nuristan',
    icon: ProvinceIcon,
    value: 'nuristan',
    districts: [
      { value: 'barg_i_matal', label: 'Barg-i Matal' },
      { value: 'du_ab', label: 'Du Ab' },
      { value: 'kamdesh', label: 'Kamdesh' },
      { value: 'mandol', label: 'Mandol' },
      { value: 'nurgram', label: 'Nurgram' },
      { value: 'parun', label: 'Parun' },
      { value: 'wama', label: 'Wama' },
      { value: 'waygal', label: 'Waygal' },
    ],
  },
  {
    id: 25,
    label: 'Paktika',
    icon: ProvinceIcon,
    value: 'paktika',
    districts: [
      { value: 'barmal', label: 'Barmal' },
      { value: 'dila', label: 'Dila' },
      { value: 'gayan', label: 'Gayan' },
      { value: 'gomal', label: 'Gomal' },
      { value: 'janikhel', label: 'Janikhel' },
      { value: 'khairkot', label: 'Khairkot' },
      { value: 'mata_khan', label: 'Mata Khan' },
      { value: 'nika', label: 'Nika' },
      { value: 'omna', label: 'Omna' },
      { value: 'sar_hawza', label: 'Sar Hawza' },
      { value: 'surobi', label: 'Surobi' },
      { value: 'sharana', label: 'Sharana' },
      { value: 'terwa', label: 'Terwa' },
      { value: 'urgun', label: 'Urgun' },
      { value: 'wazakhwa', label: 'Wazakhwa' },
      { value: 'wor_mamay', label: 'Wor Mamay' },
      { value: 'yahyakhel', label: 'Yahyakhel' },
      { value: 'yusufkhel', label: 'Yusufkhel' },
      { value: 'zerok', label: 'Zerok' },
    ],
  },
  {
    id: 26,
    label: 'Paktia',
    icon: ProvinceIcon,
    value: 'paktia',
    districts: [
      { value: 'ahmad_aba', label: 'Ahmad Aba' },
      { value: 'ahmadkhel', label: 'Ahmadkhel' },
      { value: 'dand_aw_patan', label: 'Dand Aw Patan' },
      { value: 'gardez', label: 'Gardez' },
      { value: 'gerda_serai', label: 'Gerda Serai' },
      { value: 'janikhel', label: 'Janikhel' },
      { value: 'laja_mangal', label: 'Laja Mangal' },
      { value: 'mirzaka', label: 'Mirzaka' },
      { value: 'rohani_baba', label: 'Rohani Baba' },
      { value: 'said_karam', label: 'Said Karam' },
      { value: 'shwak', label: 'Shwak' },
      { value: 'chamkani', label: 'Chamkani' },
      { value: 'zadran', label: 'Zadran' },
      { value: 'zazi', label: 'Zazi' },
      { value: 'zurmat', label: 'Zurmat' },
    ],
  },
  {
    id: 27,
    label: 'Panjshir',
    icon: ProvinceIcon,
    value: 'panjshir',
    districts: [
      { value: 'abshar', label: 'Abshar' },
      { value: 'anaba', label: 'Anaba' },
      { value: 'bazarak', label: 'Bazarak' },
      { value: 'darah', label: 'Darah' },
      { value: 'khenj', label: 'Khenj' },
      { value: 'paryan', label: 'Paryan' },
      { value: 'rokha', label: 'Rokha' },
      { value: 'shotul', label: 'Shotul' },
    ],
  },
  {
    id: 28,
    label: 'Parwan',
    icon: ProvinceIcon,
    value: 'parwan',
    districts: [
      { value: 'bagram', label: 'Bagram' },
      { value: 'charikar', label: 'Charikar' },
      { value: 'ghorband', label: 'Ghorband' },
      { value: 'jabal_saraj', label: 'Jabal Saraj' },
      { value: 'kohi_safi', label: 'Kohi Safi' },
      { value: 'salang', label: 'Salang' },
      { value: 'sayed_khel', label: 'Sayed Khel' },
      { value: 'sheikh_ali', label: 'Sheikh Ali' },
      { value: 'shinwari', label: 'Shinwari' },
      { value: 'surkhi_parsa', label: 'Surkhi Parsa' },
    ],
  },
  {
    id: 29,
    label: 'Samangan',
    icon: ProvinceIcon,
    value: 'samangan',
    districts: [
      { value: 'aybak', label: 'Aybak' },
      { value: 'darah_sof_balla', label: 'Darah Sof Balla' },
      { value: 'darah_sof_payan', label: 'Darah Sof Payan' },
      { value: 'feroz_nakhchir', label: 'Feroz Nakhchir' },
      { value: 'hazrat_sultan', label: 'Hazrat Sultan' },
      { value: 'khuram_wa_sarbagh', label: 'Khuram Wa Sarbagh' },
      { value: 'ruyi_du_ab', label: 'Ruyi Du Ab' },
    ],
  },
  {
    id: 30,
    label: 'Sar-e Pol',
    icon: ProvinceIcon,
    value: 'sar-e-pol',
    districts: [
      { value: 'balkhab', label: 'Balkhab' },
      { value: 'gosfandi', label: 'Gosfandi' },
      { value: 'kohistanat', label: 'Kohistanat' },
      { value: 'sanchark', label: 'Sancharak' },
      { value: 'sare_pol', label: 'Sare-Pol' },
      { value: 'sayyad', label: 'Sayyad' },
      { value: 'sozma_qala', label: 'Sozma Qala' },
    ],
  },
  {
    id: 31,
    label: 'Takhar',
    icon: ProvinceIcon,
    value: 'takhar',
    districts: [
      { value: 'baharak', label: 'Baharak' },
      { value: 'bangi', label: 'Bangi' },
      { value: 'chah_ab', label: 'Chah Ab' },
      { value: 'chal', label: 'Chal' },
      { value: 'darqad', label: 'Darqad' },
      { value: 'dashti_qala', label: 'Dashti Qala' },
      { value: 'farkhar', label: 'Farkhar' },
      { value: 'hazar_sumuch', label: 'Hazar Sumuch' },
      { value: 'ishkamish', label: 'Ishkamish' },
      { value: 'kalafgan', label: 'Kalafgan' },
      { value: 'khwaja_bahauddin', label: 'Khwaja Bahauddin' },
      { value: 'khwaja_ghar', label: 'Khwaja Ghar' },
      { value: 'namak_ab', label: 'Namak Ab' },
      { value: 'rustaq', label: 'Rustaq' },
      { value: 'taluqan', label: 'Taluqan' },
      { value: 'warsaj', label: 'Warsaj' },
      { value: 'yangi_qala', label: 'Yangi Qala' },
    ],
  },
  {
    id: 32,
    label: 'Uruzgan',
    icon: ProvinceIcon,
    value: 'uruzgan',
    districts: [
      { value: 'shahidi_hassas', label: 'Shahidi Hassas' },
      { value: 'chora', label: 'Chora' },
      { value: 'deh_rawood', label: 'Deh Rawood' },
      { value: 'gizab', label: 'Gizab' },
      { value: 'khas_uruzgan', label: 'Khas Uruzgan' },
      { value: 'tarinkot', label: 'Tarinkot' },
    ],
  },
  {
    id: 33,
    label: 'Wardak',
    icon: ProvinceIcon,
    value: 'wardak',
    districts: [
      { value: 'chaki_wardak', label: 'Chaki Wardak' },
      { value: 'day_mirdad', label: 'Day Mirdad' },
      { value: 'hisa_i_awali_bihsud', label: 'Hisa-I-Awali Bihsud' },
      { value: 'jaghatu', label: 'Jaghatu' },
      { value: 'jalrez', label: 'Jalrez' },
      { value: 'markazi_bihsud', label: 'Markazi Bihsud' },
      { value: 'maidan_shar', label: 'Maidan Shar' },
      { value: 'nirkh', label: 'Nirkh' },
      { value: 'saydabad', label: 'Saydabad' },
    ],
  },
  {
    id: 34,
    label: 'Zabul',
    icon: ProvinceIcon,
    value: 'zabul',
    districts: [
      { value: 'arghandab', label: 'Arghandab' },
      { value: 'atghar', label: 'Atghar' },
      { value: 'daychopan', label: 'Daychopan' },
      { value: 'kakar', label: 'Kakar' },
      { value: 'mezana', label: 'Mezana' },
      { value: 'naw_bahar', label: 'Naw Bahar' },
      { value: 'qalat', label: 'Qalat' },
      { value: 'shah_joy', label: 'Shah Joy' },
      { value: 'shamulzayi', label: 'Shamulzayi' },
      { value: 'shinkay', label: 'Shinkay' },
      { value: 'tarnak_aw_jaldak', label: 'Tarnak Aw Jaldak' },
    ],
  },
]
