import { Categorytype } from '@shared/ui/category/types'
import { MdOutlineLocationOn } from 'react-icons/md'

const ProvinceIcon = <MdOutlineLocationOn size={20} />

export const CurrencyConstants = [
  { value: 'AFN', label: 'currency.afn' },
  { value: 'USD', label: 'currency.usd' },
] as const

export const ProvinceConstants: (Categorytype & {
  districts: { value: string; label: any }[]
})[] = [
  {
    id: 1,
    label: 'provinces.badakhshan',
    icon: ProvinceIcon,
    value: 'badakhshan',
    districts: [
      { value: 'arghanj_khwa', label: 'districts.arghanj_khwa' },
      { value: 'argo', label: 'districts.argo' },
      { value: 'baharak', label: 'districts.baharak' },
      { value: 'darayim', label: 'districts.darayim' },
      { value: 'fayzabad', label: 'districts.fayzabad' },
      { value: 'ishkashim', label: 'districts.ishkashim' },
      { value: 'jurm', label: 'districts.jurm' },
      { value: 'khash', label: 'districts.khash' },
      { value: 'khwahan', label: 'districts.khwahan' },
      { value: 'kishim', label: 'districts.kishim' },
      { value: 'kohistan', label: 'districts.kohistan' },
      { value: 'kuf_ab', label: 'districts.kuf_ab' },
      { value: 'kuran_wa_munjan', label: 'districts.kuran_wa_munjan' },
      { value: 'maimay', label: 'districts.maimay' },
      { value: 'nusay', label: 'districts.nusay' },
      { value: 'raghistan', label: 'districts.raghistan' },
      { value: 'shahri_buzurg', label: 'districts.shahri_buzurg' },
      { value: 'sheghnan', label: 'districts.sheghnan' },
      { value: 'shekay', label: 'districts.shekay' },
      { value: 'shuhada', label: 'districts.shuhada' },
      { value: 'tagab', label: 'districts.tagab' },
      { value: 'tishkan', label: 'districts.tishkan' },
      { value: 'wakhan', label: 'districts.wakhan' },
      { value: 'warduj', label: 'districts.warduj' },
      { value: 'yaftali_sufla', label: 'districts.yaftali_sufla' },
      { value: 'yamgan', label: 'districts.yamgan' },
      { value: 'yawan', label: 'districts.yawan' },
      { value: 'zebak', label: 'districts.zebak' },
    ],
  },
  {
    id: 2,
    label: 'provinces.badghis',
    icon: ProvinceIcon,
    value: 'badghis',
    districts: [
      { value: 'ab_kamari', label: 'districts.ab_kamari' },
      { value: 'ghormach', label: 'districts.ghormach' },
      { value: 'jawand', label: 'districts.jawand' },
      { value: 'muqur', label: 'districts.muqur' },
      { value: 'bala_murghab', label: 'districts.bala_murghab' },
      { value: 'qadis', label: 'districts.qadis' },
      { value: 'qala_i_naw', label: 'districts.qala_i_naw' },
    ],
  },
  {
    id: 3,
    label: 'provinces.baghlan',
    icon: ProvinceIcon,
    value: 'baghlan',
    districts: [
      { value: 'andarab', label: 'districts.andarab' },
      { value: 'baghlani_jadid', label: 'districts.baghlani_jadid' },
      { value: 'burka', label: 'districts.burka' },
      { value: 'dahana_i_ghuri', label: 'districts.dahana_i_ghuri' },
      { value: 'dih_salah', label: 'districts.dih_salah' },
      { value: 'dushi', label: 'districts.dushi' },
      { value: 'farang_wa_gharu', label: 'districts.farang_wa_gharu' },
      { value: 'guzargahi_nur', label: 'districts.guzargahi_nur' },
      { value: 'khinjan', label: 'districts.khinjan' },
      { value: 'khost_wa_fereng', label: 'districts.khost_wa_fereng' },
      { value: 'khwaja_hijran', label: 'districts.khwaja_hijran' },
      { value: 'nahrin', label: 'districts.nahrin' },
      { value: 'puli_hisar', label: 'districts.puli_hisar' },
      { value: 'puli_khumri', label: 'districts.puli_khumri' },
      { value: 'tala_wa_barfak', label: 'districts.tala_wa_barfak' },
    ],
  },
  {
    id: 4,
    label: 'provinces.balkh',
    icon: ProvinceIcon,
    value: 'balkh',
    districts: [
      { value: 'balkh', label: 'districts.balkh' },
      { value: 'charbolak', label: 'districts.charbolak' },
      { value: 'charkint', label: 'districts.charkint' },
      { value: 'chimtal', label: 'districts.chimtal' },
      { value: 'dawlatabad', label: 'districts.dawlatabad' },
      { value: 'dihdadi', label: 'districts.dihdadi' },
      { value: 'kaldar', label: 'districts.kaldar' },
      { value: 'khulm', label: 'districts.khulm' },
      { value: 'kishindih', label: 'districts.kishindih' },
      { value: 'marmul', label: 'districts.marmul' },
      { value: 'mazar_e_sharif', label: 'districts.mazar_e_sharif' },
      { value: 'nahri_shahi', label: 'districts.nahri_shahi' },
      { value: 'sholgara', label: 'districts.sholgara' },
      { value: 'shortepa', label: 'districts.shortepa' },
      { value: 'zari', label: 'districts.zari' },
    ],
  },
  {
    id: 5,
    label: 'provinces.bamyan',
    icon: ProvinceIcon,
    value: 'bamyan',
    districts: [
      { value: 'bamyan', label: 'districts.bamyan' },
      { value: 'kahmard', label: 'districts.kahmard' },
      { value: 'panjab', label: 'districts.panjab' },
      { value: 'sayghan', label: 'districts.sayghan' },
      { value: 'shibar', label: 'districts.shibar' },
      { value: 'waras', label: 'districts.waras' },
      { value: 'yakawlang', label: 'districts.yakawlang' },
    ],
  },
  {
    id: 6,
    label: 'provinces.daykundi',
    icon: ProvinceIcon,
    value: 'daykundi',
    districts: [
      { value: 'ishtarlay', label: 'districts.ishtarlay' },
      { value: 'kijran', label: 'districts.kijran' },
      { value: 'khedir', label: 'districts.khedir' },
      { value: 'kitti', label: 'districts.kitti' },
      { value: 'miramor', label: 'districts.miramor' },
      { value: 'nili', label: 'districts.nili' },
      { value: 'sangi_takht', label: 'districts.sangi_takht' },
      { value: 'shahristan', label: 'districts.shahristan' },
    ],
  },
  {
    id: 7,
    label: 'provinces.farah',
    icon: ProvinceIcon,
    value: 'farah',
    districts: [
      { value: 'anar_dara', label: 'districts.anar_dara' },
      { value: 'bakwa', label: 'districts.bakwa' },
      { value: 'bala_buluk', label: 'districts.bala_buluk' },
      { value: 'farah', label: 'districts.farah' },
      { value: 'gulistan', label: 'districts.gulistan' },
      { value: 'khaki_safed', label: 'districts.khaki_safed' },
      { value: 'lash_wa_juwayn', label: 'districts.lash_wa_juwayn' },
      { value: 'pur_chaman', label: 'districts.pur_chaman' },
      { value: 'pusht_rod', label: 'districts.pusht_rod' },
      { value: 'qala_i_kah', label: 'districts.qala_i_kah' },
      { value: 'shib_koh', label: 'districts.shib_koh' },
    ],
  },
  {
    id: 8,
    label: 'provinces.faryab',
    icon: ProvinceIcon,
    value: 'faryab',
    districts: [
      { value: 'almar', label: 'districts.almar' },
      { value: 'andkhoy', label: 'districts.andkhoy' },
      { value: 'bilchiragh', label: 'districts.bilchiragh' },
      { value: 'dawlat_abad', label: 'districts.dawlat_abad' },
      { value: 'gurziwan', label: 'districts.gurziwan' },
      { value: 'khani_char_bagh', label: 'districts.khani_char_bagh' },
      { value: 'khwaja_sabz_posh', label: 'districts.khwaja_sabz_posh' },
      { value: 'kohistan', label: 'districts.kohistan' },
      { value: 'maymana', label: 'districts.maymana' },
      { value: 'pashtun_kot', label: 'districts.pashtun_kot' },
      { value: 'qaramqol', label: 'districts.qaramqol' },
      { value: 'qaysar', label: 'districts.qaysar' },
      { value: 'qurghan', label: 'districts.qurghan' },
      { value: 'shirin_tagab', label: 'districts.shirin_tagab' },
    ],
  },
  {
    id: 9,
    label: 'provinces.ghazni',
    icon: ProvinceIcon,
    value: 'ghazni',
    districts: [
      { value: 'ab_band', label: 'districts.ab_band' },
      { value: 'ajristan', label: 'districts.ajristan' },
      { value: 'andar', label: 'districts.andar' },
      { value: 'deh_yak', label: 'districts.deh_yak' },
      { value: 'gelan', label: 'districts.gelan' },
      { value: 'ghazni', label: 'districts.ghazni' },
      { value: 'giro', label: 'districts.giro' },
      { value: 'jaghori', label: 'districts.jaghori' },
      { value: 'jaghatu', label: 'districts.jaghatu' },
      { value: 'khogyani', label: 'districts.khogyani' },
      { value: 'khwaja_umari', label: 'districts.khwaja_umari' },
      { value: 'malistan', label: 'districts.malistan' },
      { value: 'muqur', label: 'districts.muqur' },
      { value: 'nawa', label: 'districts.nawa' },
      { value: 'nawur', label: 'districts.nawur' },
      { value: 'qarabagh', label: 'districts.qarabagh' },
      { value: 'rashidan', label: 'districts.rashidan' },
      { value: 'waghaz', label: 'districts.waghaz' },
      { value: 'zana_khan', label: 'districts.zana_khan' },
    ],
  },
  {
    id: 10,
    label: 'provinces.ghor',
    icon: ProvinceIcon,
    value: 'ghor',
    districts: [
      { value: 'chaghcharan', label: 'districts.chaghcharan' },
      { value: 'charsada', label: 'districts.charsada' },
      { value: 'dawlat_yar', label: 'districts.dawlat_yar' },
      { value: 'du_layna', label: 'districts.du_layna' },
      { value: 'lal_wa_sarjangal', label: 'districts.lal_wa_sarjangal' },
      { value: 'marghab', label: 'districts.marghab' },
      { value: 'pasaband', label: 'districts.pasaband' },
      { value: 'saghar', label: 'districts.saghar' },
      { value: 'shahrak', label: 'districts.shahrak' },
      { value: 'taywara', label: 'districts.taywara' },
      { value: 'tulak', label: 'districts.tulak' },
    ],
  },
  {
    id: 11,
    label: 'provinces.helmand',
    icon: ProvinceIcon,
    value: 'helmand',
    districts: [
      { value: 'baghran', label: 'districts.baghran' },
      { value: 'dishu', label: 'districts.dishu' },
      { value: 'garmsir', label: 'districts.garmsir' },
      { value: 'kajaki', label: 'districts.kajaki' },
      { value: 'khanashin', label: 'districts.khanashin' },
      { value: 'lashkargah', label: 'districts.lashkargah' },
      { value: 'marjah', label: 'districts.marjah' },
      { value: 'musa_qala', label: 'districts.musa_qala' },
      { value: 'nad_ali', label: 'districts.nad_ali' },
      { value: 'grishk', label: 'districts.grishk' },
      { value: 'nawa_i_barakzayi', label: 'districts.nawa_i_barakzayi' },
      { value: 'nawzad', label: 'districts.nawzad' },
      { value: 'sangin', label: 'districts.sangin' },
      { value: 'washir', label: 'districts.washir' },
    ],
  },
  {
    id: 12,

    label: 'provinces.herat',
    icon: ProvinceIcon,
    value: 'herat',
    districts: [
      { value: 'adraskan', label: 'districts.adraskan' },
      { value: 'chishti_sharif', label: 'districts.chishti_sharif' },
      { value: 'farsi', label: 'districts.farsi' },
      { value: 'ghoryan', label: 'districts.ghoryan' },
      { value: 'gulran', label: 'districts.gulran' },
      { value: 'guzara', label: 'districts.guzara' },
      { value: 'herat', label: 'districts.herat' },
      { value: 'injil', label: 'districts.injil' },
      { value: 'karukh', label: 'districts.karukh' },
      { value: 'kohsan', label: 'districts.kohsan' },
      { value: 'kushk', label: 'districts.kushk' },
      { value: 'kushki_kuhna', label: 'districts.kushki_kuhna' },
      { value: 'obe', label: 'districts.obe' },
      { value: 'pashtun_zarghun', label: 'districts.pashtun_zarghun' },
      { value: 'shindand', label: 'districts.shindand' },
      { value: 'zinda_jan', label: 'districts.zinda_jan' },
    ],
  },
  {
    id: 13,

    label: 'provinces.jowzjan',
    icon: ProvinceIcon,
    value: 'jowzjan',
    districts: [
      { value: 'aqcha', label: 'districts.aqcha' },
      { value: 'darzab', label: 'districts.darzab' },
      { value: 'fayzabad', label: 'districts.fayzabad' },
      { value: 'khamyab', label: 'districts.khamyab' },
      { value: 'khaniqa', label: 'districts.khaniqa' },
      { value: 'khwaja_du_koh', label: 'districts.khwaja_du_koh' },
      { value: 'mardyan', label: 'districts.mardyan' },
      { value: 'mingajik', label: 'districts.mingajik' },
      { value: 'qarqin', label: 'districts.qarqin' },
      { value: 'qush_tepa', label: 'districts.qush_tepa' },
      { value: 'sheberghan', label: 'districts.sheberghan' },
    ],
  },
  {
    id: 14,

    label: 'provinces.kabul',
    icon: ProvinceIcon,
    value: 'kabul',
    districts: [
      { value: 'bagrami', label: 'districts.bagrami' },
      { value: 'chahar_asyab', label: 'districts.chahar_asyab' },
      { value: 'deh_sabz', label: 'districts.deh_sabz' },
      { value: 'farza', label: 'districts.farza' },
      { value: 'guldara', label: 'districts.guldara' },
      { value: 'istalif', label: 'districts.istalif' },
      { value: 'kabul', label: 'districts.kabul' },
      { value: 'kalakan', label: 'districts.kalakan' },
      { value: 'khaki_jabbar', label: 'districts.khaki_jabbar' },
      { value: 'mir_bacha_kot', label: 'districts.mir_bacha_kot' },
      { value: 'mussahi', label: 'districts.mussahi' },
      { value: 'paghman', label: 'districts.paghman' },
      { value: 'qarabagh', label: 'districts.qarabagh' },
      { value: 'shakardara', label: 'districts.shakardara' },
      { value: 'surobi', label: 'districts.surobi' },
    ],
  },
  {
    id: 15,

    label: 'provinces.kandahar',
    icon: ProvinceIcon,
    value: 'kandahar',
    districts: [
      { value: 'arghandab', label: 'districts.arghandab' },
      { value: 'arghistan', label: 'districts.arghistan' },
      { value: 'daman', label: 'districts.daman' },
      { value: 'ghorak', label: 'districts.ghorak' },
      { value: 'kandahar', label: 'districts.kandahar' },
      { value: 'khakrez', label: 'districts.khakrez' },
      { value: 'maruf', label: 'districts.maruf' },
      { value: 'maiwand', label: 'districts.maiwand' },
      { value: 'miyanishin', label: 'districts.miyanishin' },
      { value: 'nesh', label: 'districts.nesh' },
      { value: 'panjwayi', label: 'districts.panjwayi' },
      { value: 'reg', label: 'districts.reg' },
      { value: 'shah_wali_kot', label: 'districts.shah_wali_kot' },
      { value: 'shorabak', label: 'districts.shorabak' },
      { value: 'spin_boldak', label: 'districts.spin_boldak' },
      { value: 'takhta_pul', label: 'districts.takhta_pul' },
      { value: 'zhari', label: 'districts.zhari' },
      { value: 'dand', label: 'districts.dand' },
    ],
  },
  {
    id: 16,

    label: 'provinces.kapisa',
    icon: ProvinceIcon,
    value: 'kapisa',
    districts: [
      { value: 'alasay', label: 'districts.alasay' },
      { value: 'hesa_awal_kohistan', label: 'districts.hesa_awal_kohistan' },
      { value: 'hesa_duwum_kohistan', label: 'districts.hesa_duwum_kohistan' },
      { value: 'koh_band', label: 'districts.koh_band' },
      { value: 'mahmud_raqi', label: 'districts.mahmud_raqi' },
      { value: 'nijrab', label: 'districts.nijrab' },
      { value: 'tagab', label: 'districts.tagab' },
    ],
  },
  {
    id: 17,

    label: 'provinces.khost',
    icon: ProvinceIcon,
    value: 'khost',
    districts: [
      { value: 'bak', label: 'districts.bak' },
      { value: 'gurbuz', label: 'districts.gurbuz' },
      { value: 'jaji_maydan', label: 'districts.jaji_maydan' },
      { value: 'khost', label: 'districts.khost' },
      { value: 'mandozayi', label: 'districts.mandozayi' },
      { value: 'musa_khel', label: 'districts.musa_khel' },
      { value: 'nadir_shah_kot', label: 'districts.nadir_shah_kot' },
      { value: 'qalandar', label: 'districts.qalandar' },
      { value: 'sabari', label: 'districts.sabari' },
      { value: 'shamal', label: 'districts.shamal' },
      { value: 'spera', label: 'districts.spera' },
      { value: 'tani', label: 'districts.tani' },
      { value: 'tirazayi', label: 'districts.tirazayi' },
    ],
  },
  {
    id: 18,

    label: 'provinces.kunar',
    icon: ProvinceIcon,
    value: 'kunar',
    districts: [
      { value: 'asadabad', label: 'districts.asadabad' },
      { value: 'bar_kunar', label: 'districts.bar_kunar' },
      { value: 'chapa_dara', label: 'districts.chapa_dara' },
      { value: 'chawkay', label: 'districts.chawkay' },
      { value: 'dangam', label: 'districts.dangam' },
      { value: 'dara_i_pech', label: 'districts.dara_i_pech' },
      { value: 'ghaziabad', label: 'districts.ghaziabad' },
      { value: 'khas_kunar', label: 'districts.khas_kunar' },
      { value: 'marawara', label: 'districts.marawara' },
      { value: 'narang_aw_badil', label: 'districts.narang_aw_badil' },
      { value: 'nari', label: 'districts.nari' },
      { value: 'nurgal', label: 'districts.nurgal' },
      { value: 'shaigal', label: 'districts.shaigal' },
      { value: 'shultan', label: 'districts.shultan' },
      { value: 'sirkani', label: 'districts.sirkani' },
      { value: 'wata_pur', label: 'districts.wata_pur' },
    ],
  },
  {
    id: 19,
    label: 'provinces.kunduz',
    icon: ProvinceIcon,
    value: 'kunduz',
    districts: [
      { value: 'ali_abad', label: 'districts.ali_abad' },
      { value: 'archi', label: 'districts.archi' },
      { value: 'chardara', label: 'districts.chardara' },
      { value: 'imam_sahib', label: 'districts.imam_sahib' },
      { value: 'khan_abad', label: 'districts.khan_abad' },
      { value: 'kunduz', label: 'districts.kunduz' },
      { value: 'qalay_i_zal', label: 'districts.qalay_i_zal' },
    ],
  },
  {
    id: 20,
    label: 'provinces.laghman',
    icon: ProvinceIcon,
    value: 'laghman',
    districts: [
      { value: 'alingar', label: 'districts.alingar' },
      { value: 'alishing', label: 'districts.alishing' },
      { value: 'dawlat_shah', label: 'districts.dawlat_shah' },
      { value: 'mihtarlam', label: 'districts.mihtarlam' },
      { value: 'qarghayi', label: 'districts.qarghayi' },
    ],
  },
  {
    id: 21,
    label: 'provinces.logar',
    icon: ProvinceIcon,
    value: 'logar',
    districts: [
      { value: 'azra', label: 'districts.azra' },
      { value: 'baraki_barak', label: 'districts.baraki_barak' },
      { value: 'charkh', label: 'districts.charkh' },
      { value: 'kharwar', label: 'districts.kharwar' },
      { value: 'khoshi', label: 'districts.khoshi' },
      { value: 'mohammad_agha', label: 'districts.mohammad_agha' },
      { value: 'puli_alam', label: 'districts.puli_alam' },
    ],
  },
  {
    id: 22,
    label: 'provinces.nangarhar',
    icon: ProvinceIcon,
    value: 'nangarhar',
    districts: [
      { value: 'jalalabad', label: 'districts.jalalabad' },
      { value: 'haska_meyna', label: 'districts.haska_meyna' },
      { value: 'shinwar', label: 'districts.shinwar' },
      { value: 'achin', label: 'districts.achin' },
      { value: 'bihsud', label: 'districts.bihsud' },
      { value: 'chaparhar', label: 'districts.chaparhar' },
      { value: 'darai_nur', label: 'districts.darai_nur' },
      { value: 'bati_kot', label: 'districts.bati_kot' },
      { value: 'dur_baba', label: 'districts.dur_baba' },
      { value: 'goshta', label: 'districts.goshta' },
      { value: 'hisarak', label: 'districts.hisarak' },
      { value: 'kama', label: 'districts.kama' },
      { value: 'khogyani', label: 'districts.khogyani' },
      { value: 'kot', label: 'districts.kot' },
      { value: 'kuz_kunar', label: 'districts.kuz_kunar' },
      { value: 'lal_pur', label: 'districts.lal_pur' },
      { value: 'momand_dara', label: 'districts.momand_dara' },
      { value: 'nazyan', label: 'districts.nazyan' },
      { value: 'pachir_aw_agam', label: 'districts.pachir_aw_agam' },
      { value: 'rodat', label: 'districts.rodat' },
      { value: 'sherzad', label: 'districts.sherzad' },
      { value: 'surkh_rod', label: 'districts.surkh_rod' },
    ],
  },
  {
    id: 23,
    label: 'provinces.nimroz',
    icon: ProvinceIcon,
    value: 'nimroz',
    districts: [
      { value: 'chahar_burjak', label: 'districts.chahar_burjak' },
      { value: 'chakhansur', label: 'districts.chakhansur' },
      { value: 'kang', label: 'districts.kang' },
      { value: 'khash_rod', label: 'districts.khash_rod' },
      { value: 'zaranj', label: 'districts.zaranj' },
    ],
  },
  {
    id: 24,
    label: 'provinces.nuristan',
    icon: ProvinceIcon,
    value: 'nuristan',
    districts: [
      { value: 'barg_i_matal', label: 'districts.barg_i_matal' },
      { value: 'du_ab', label: 'districts.du_ab' },
      { value: 'kamdesh', label: 'districts.kamdesh' },
      { value: 'mandol', label: 'districts.mandol' },
      { value: 'nurgram', label: 'districts.nurgram' },
      { value: 'parun', label: 'districts.parun' },
      { value: 'wama', label: 'districts.wama' },
      { value: 'waygal', label: 'districts.waygal' },
    ],
  },
  {
    id: 25,
    label: 'provinces.paktika',
    icon: ProvinceIcon,
    value: 'paktika',
    districts: [
      { value: 'barmal', label: 'districts.barmal' },
      { value: 'dila', label: 'districts.dila' },
      { value: 'gayan', label: 'districts.gayan' },
      { value: 'gomal', label: 'districts.gomal' },
      { value: 'janikhel', label: 'districts.janikhel' },
      { value: 'khairkot', label: 'districts.khairkot' },
      { value: 'mata_khan', label: 'districts.mata_khan' },
      { value: 'nika', label: 'districts.nika' },
      { value: 'omna', label: 'districts.omna' },
      { value: 'sar_hawza', label: 'districts.sar_hawza' },
      { value: 'surobi', label: 'districts.surobi' },
      { value: 'sharana', label: 'districts.sharana' },
      { value: 'terwa', label: 'districts.terwa' },
      { value: 'urgun', label: 'districts.urgun' },
      { value: 'wazakhwa', label: 'districts.wazakhwa' },
      { value: 'wor_mamay', label: 'districts.wor_mamay' },
      { value: 'yahyakhel', label: 'districts.yahyakhel' },
      { value: 'yusufkhel', label: 'districts.yusufkhel' },
      { value: 'zerok', label: 'districts.zerok' },
    ],
  },
  {
    id: 26,
    label: 'provinces.paktia',
    icon: ProvinceIcon,
    value: 'paktia',
    districts: [
      { value: 'ahmad_aba', label: 'districts.ahmad_aba' },
      { value: 'ahmadkhel', label: 'districts.ahmadkhel' },
      { value: 'dand_aw_patan', label: 'districts.dand_aw_patan' },
      { value: 'gardez', label: 'districts.gardez' },
      { value: 'gerda_serai', label: 'districts.gerda_serai' },
      { value: 'janikhel', label: 'districts.janikhel' },
      { value: 'laja_mangal', label: 'districts.laja_mangal' },
      { value: 'mirzaka', label: 'districts.mirzaka' },
      { value: 'rohani_baba', label: 'districts.rohani_baba' },
      { value: 'said_karam', label: 'districts.said_karam' },
      { value: 'shwak', label: 'districts.shwak' },
      { value: 'chamkani', label: 'districts.chamkani' },
      { value: 'zadran', label: 'districts.zadran' },
      { value: 'zazi', label: 'districts.zazi' },
      { value: 'zurmat', label: 'districts.zurmat' },
    ],
  },
  {
    id: 27,
    label: 'provinces.panjshir',
    icon: ProvinceIcon,
    value: 'panjshir',
    districts: [
      { value: 'abshar', label: 'districts.abshar' },
      { value: 'anaba', label: 'districts.anaba' },
      { value: 'bazarak', label: 'districts.bazarak' },
      { value: 'darah', label: 'districts.darah' },
      { value: 'khenj', label: 'districts.khenj' },
      { value: 'paryan', label: 'districts.paryan' },
      { value: 'rokha', label: 'districts.rokha' },
      { value: 'shotul', label: 'districts.shotul' },
    ],
  },
  {
    id: 28,
    label: 'provinces.parwan',
    icon: ProvinceIcon,
    value: 'parwan',
    districts: [
      { value: 'bagram', label: 'districts.bagram' },
      { value: 'charikar', label: 'districts.charikar' },
      { value: 'ghorband', label: 'districts.ghorband' },
      { value: 'jabal_saraj', label: 'districts.jabal_saraj' },
      { value: 'kohi_safi', label: 'districts.kohi_safi' },
      { value: 'salang', label: 'districts.salang' },
      { value: 'sayed_khel', label: 'districts.sayed_khel' },
      { value: 'sheikh_ali', label: 'districts.sheikh_ali' },
      { value: 'shinwari', label: 'districts.shinwari' },
      { value: 'surkhi_parsa', label: 'districts.surkhi_parsa' },
    ],
  },
  {
    id: 29,
    label: 'provinces.samangan',
    icon: ProvinceIcon,
    value: 'samangan',
    districts: [
      { value: 'aybak', label: 'districts.aybak' },
      { value: 'darah_sof_balla', label: 'districts.darah_sof_balla' },
      { value: 'darah_sof_payan', label: 'districts.darah_sof_payan' },
      { value: 'feroz_nakhchir', label: 'districts.feroz_nakhchir' },
      { value: 'hazrat_sultan', label: 'districts.hazrat_sultan' },
      { value: 'khuram_wa_sarbagh', label: 'districts.khuram_wa_sarbagh' },
      { value: 'ruyi_du_ab', label: 'districts.ruyi_du_ab' },
    ],
  },
  {
    id: 30,
    label: 'provinces.sar-e-pol',
    icon: ProvinceIcon,
    value: 'sar-e-pol',
    districts: [
      { value: 'balkhab', label: 'districts.balkhab' },
      { value: 'gosfandi', label: 'districts.gosfandi' },
      { value: 'kohistanat', label: 'districts.kohistanat' },
      { value: 'sanchark', label: 'districts.sanchark' },
      { value: 'sare_pol', label: 'districts.sare_pol' },
      { value: 'sayyad', label: 'districts.sayyad' },
      { value: 'sozma_qala', label: 'districts.sozma_qala' },
    ],
  },
  {
    id: 31,
    label: 'provinces.takhar',
    icon: ProvinceIcon,
    value: 'takhar',
    districts: [
      { value: 'baharak', label: 'districts.baharak' },
      { value: 'bangi', label: 'districts.bangi' },
      { value: 'chah_ab', label: 'districts.chah_ab' },
      { value: 'chal', label: 'districts.chal' },
      { value: 'darqad', label: 'districts.darqad' },
      { value: 'dashti_qala', label: 'districts.dashti_qala' },
      { value: 'farkhar', label: 'districts.farkhar' },
      { value: 'hazar_sumuch', label: 'districts.hazar_sumuch' },
      { value: 'ishkamish', label: 'districts.ishkamish' },
      { value: 'kalafgan', label: 'districts.kalafgan' },
      { value: 'khwaja_bahauddin', label: 'districts.khwaja_bahauddin' },
      { value: 'khwaja_ghar', label: 'districts.khwaja_ghar' },
      { value: 'namak_ab', label: 'districts.namak_ab' },
      { value: 'rustaq', label: 'districts.rustaq' },
      { value: 'taluqan', label: 'districts.taluqan' },
      { value: 'warsaj', label: 'districts.warsaj' },
      { value: 'yangi_qala', label: 'districts.yangi_qala' },
    ],
  },
  {
    id: 32,
    label: 'provinces.uruzgan',
    icon: ProvinceIcon,
    value: 'uruzgan',
    districts: [
      { value: 'shahidi_hassas', label: 'districts.shahidi_hassas' },
      { value: 'chora', label: 'districts.chora' },
      { value: 'deh_rawood', label: 'districts.deh_rawood' },
      { value: 'gizab', label: 'districts.gizab' },
      { value: 'khas_uruzgan', label: 'districts.khas_uruzgan' },
      { value: 'tarinkot', label: 'districts.tarinkot' },
    ],
  },
  {
    id: 33,
    label: 'provinces.wardak',
    icon: ProvinceIcon,
    value: 'wardak',
    districts: [
      { value: 'chaki_wardak', label: 'districts.chaki_wardak' },
      { value: 'day_mirdad', label: 'districts.day_mirdad' },
      { value: 'hisa_i_awali_bihsud', label: 'districts.hisa_i_awali_bihsud' },
      { value: 'jaghatu', label: 'districts.jaghatu' },
      { value: 'jalrez', label: 'districts.jalrez' },
      { value: 'markazi_bihsud', label: 'districts.markazi_bihsud' },
      { value: 'maidan_shar', label: 'districts.maidan_shar' },
      { value: 'nirkh', label: 'districts.nirkh' },
      { value: 'saydabad', label: 'districts.saydabad' },
    ],
  },
  {
    id: 34,
    label: 'provinces.zabul',
    icon: ProvinceIcon,
    value: 'zabul',
    districts: [
      { value: 'arghandab', label: 'districts.arghandab' },
      { value: 'atghar', label: 'districts.atghar' },
      { value: 'daychopan', label: 'districts.daychopan' },
      { value: 'kakar', label: 'districts.kakar' },
      { value: 'mezana', label: 'districts.mezana' },
      { value: 'naw_bahar', label: 'districts.naw_bahar' },
      { value: 'qalat', label: 'districts.qalat' },
      { value: 'shah_joy', label: 'districts.shah_joy' },
      { value: 'shamulzayi', label: 'districts.shamulzayi' },
      { value: 'shinkay', label: 'districts.shinkay' },
      { value: 'tarnak_aw_jaldak', label: 'districts.tarnak_aw_jaldak' },
    ],
  },
]
export const defaultValues = {
  priceFrom: 0,
  priceTo: 0,
  province: '',
  district: '',
  category: '',
  currency: '',
}