export enum Paths {
  Main = '/',
  EditProfile = '/settings/edit-profile/',
  Following = '/settings/following/',
  ChangePassword = '/settings/change-password/',
  Theme = '/settings/theme/',
  Notification = '/settings/notification/',
  Privacy = '/settings/privacy/',
  ProductDetails = '/product/',
  Register = '/register',
  Login = '/login',
  ActionProduct = '/add-edit-product/',
  AddProduct = '/add-edit-product/add',
  AddProductMobile = '/model/add',
  EditProduct = '/add-edit-product/edit',
  ProfileDetails = '/profile/',
  MobileModel = '/model/',
  SecureMobileModel = '/secure-model/',
  Favorites = '/favorites/',
  Search = '/search/',
  Message = '/message/',
  MessageHistory = '/model/message-history',
  MessageList = '/model/message-list',
  NotificationStatus = '/secure-model/notification',
  FollowingStatus = '/secure-model/following',
  Forget = '/forget-password',
  Otp = '/otp',
}
