export enum Paths {
  Main = '/',
  EditProfile = '/settings/edit-profile/',
  Following = '/settings/following/',
  ChangePassword = '/settings/change-password/',
  Theme = '/settings/theme/',
  Notification = '/settings/notification/',
  Privacy = '/settings/privacy/',
  ProductDetails = '/product/',
  ProfileDetails = '/profile/',
  MobileModel = '/model/',
  Favorites = '/favorites/',
  Search = '/search/',
  Message = '/message/',
  MessageHistory = '/model/message-history',
  MessageList = '/model/message-list',
  NotificationStatus = '/model/notification',
}
