import {
  MdDirectionsCar,
  MdSmartphone,
  MdCheckroom,
  MdFaceRetouchingNatural,
  MdWeekend,
  MdChildCare,
  MdSportsSoccer,
  MdWorkOutline,
  MdHome,
  MdPets,
  MdBusinessCenter,
  MdBuild,
  MdSettingsSuggest,
  MdHotel,
} from 'react-icons/md'
import { Categorytype } from './types'

export const CategoryConstants: Categorytype[] = [
  {
    id: 1,
    value: '1',
    label: 'categories.auto',
    image: '/category/car.png',
    icon: <MdDirectionsCar size={20} />,
  },
  {
    id: 2,
    value: '2',
    label: 'categories.realEstate',
    image: '/category/home.png',
    icon: <MdHome size={20} />,
  },
  {
    id: 3,
    value: '3',
    label: 'categories.job',
    image: '/category/bag.png',
    icon: <MdWorkOutline size={20} />,
  },
  {
    id: 4,
    value: '4',
    label: 'categories.clothing',
    image: '/category/tshirt.png',
    icon: <MdCheckroom size={20} />,
  },
  {
    id: 5,
    value: '5',
    label: 'categories.hobbies',
    image: '/category/shoes.png',
    icon: <MdSportsSoccer size={20} />,
  },
  {
    id: 6,
    value: '6',
    label: 'categories.animals',
    image: '/category/animal.png',
    icon: <MdPets size={20} />,
  },
  {
    id: 7,
    value: '7',
    label: 'categories.business',
    image: '/category/printer.png',
    icon: <MdBusinessCenter size={20} />,
  },
  {
    id: 8,
    value: '8',
    label: 'categories.services',
    image: '/category/roller.png',
    icon: <MdBuild size={20} />,
  },
  {
    id: 9,
    value: '9',
    label: 'categories.electronics',
    image: '/category/phone.png',
    icon: <MdSmartphone size={20} />,
  },
  {
    id: 10,
    value: '10',
    label: 'categories.forHome',
    image: '/category/sofa.png',
    icon: <MdWeekend size={20} />,
  },
  {
    id: 11,
    value: '11',
    label: 'categories.spareParts',
    image: '/category/tyre.png',
    icon: <MdSettingsSuggest size={20} />,
  },
  {
    id: 12,
    value: '12',
    label: 'categories.children',
    image: '/category/kidscart.png',
    icon: <MdChildCare size={20} />,
  },
  {
    id: 13,
    value: '13',
    label: 'categories.accommodation',
    image: '/category/travelbag.png',
    icon: <MdHotel size={20} />,
  },
  {
    id: 14,
    value: '14',
    label: 'categories.beauty',
    image: '/category/lipstick.png',
    icon: <MdFaceRetouchingNatural size={20} />,
  },
]
